//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Busca extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JTextField jcomp4;
    private JButton btPesquisar;
    private JLabel jcomp6;
    private JTextField jcomp7;
    private JTextArea jcomp8;
    private JLabel jcomp9;
    private JLabel jcomp10;
    private JTextField jcomp11;
    private JTextField jcomp12;
    private JButton jcomp13;

    public Busca() {
        //construct components
        jcomp1 = new JLabel ("Busca");
        jcomp2 = new JLabel ("Simple Solution");
        jcomp3 = new JLabel ("Nome:");
        jcomp4 = new JTextField (5);
        btPesquisar = new JButton ("Pesquisar");
        jcomp6 = new JLabel ("Data:");
        jcomp7 = new JTextField (5);
        jcomp8 = new JTextArea (5, 5);
        jcomp9 = new JLabel ("Turma:");
        jcomp10 = new JLabel ("Nivel:");
        jcomp11 = new JTextField (5);
        jcomp12 = new JTextField (5);
        jcomp13 = new JButton ("Sair");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 366));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (btPesquisar);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (190, 40, 155, 25);
        jcomp2.setBounds (15, 15, 100, 25);
        jcomp3.setBounds (25, 100, 100, 25);
        jcomp4.setBounds (75, 100, 145, 25);
        btPesquisar.setBounds (315, 180, 100, 25);
        jcomp6.setBounds (25, 135, 100, 25);
        jcomp7.setBounds (75, 135, 100, 25);
        jcomp8.setBounds (25, 180, 275, 115);
        jcomp9.setBounds (230, 100, 100, 25);
        jcomp10.setBounds (230, 135, 100, 25);
        jcomp11.setBounds (280, 100, 100, 25);
        jcomp12.setBounds (280, 135, 100, 25);
        jcomp13.setBounds (315, 260, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Busca");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Busca());
        frame.pack();
        frame.setVisible (true);
    }
}
