//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Cadastro Responsável extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JLabel jcomp6;
    private JComboBox cbParentesco;
    private JTextField jcomp8;
    private JTextField jcomp9;
    private JLabel jcomp10;
    private JComboBox jcomp11;
    private JTextField jcomp12;
    private JLabel jcomp13;
    private JTextField jcomp14;
    private JButton btCadastrar;
    private JLabel jcomp16;
    private JTextField jcomp17;
    private JButton jcomp18;

    public Cadastro Responsável() {
        //construct preComponents
        String[] cbParentescoItems = {"Mãe", "Pai", "Irmã", "Irmão", "Tio", "Tia", "Avó", "Avô", "Responsável legal"};
        String[] jcomp11Items = {"F", "M", "G", "L", "T", "N/B", "N/A"};

        //construct components
        jcomp1 = new JLabel ("Cadastro de Responsável");
        jcomp2 = new JLabel ("Simple Solution");
        jcomp3 = new JLabel ("Nome:");
        jcomp4 = new JLabel ("Data Nasc. :");
        jcomp5 = new JLabel ("Cidade:");
        jcomp6 = new JLabel ("Parentesco :");
        cbParentesco = new JComboBox (cbParentescoItems);
        jcomp8 = new JTextField (5);
        jcomp9 = new JTextField (5);
        jcomp10 = new JLabel ("Sexo:");
        jcomp11 = new JComboBox (jcomp11Items);
        jcomp12 = new JTextField (5);
        jcomp13 = new JLabel ("Endereço:");
        jcomp14 = new JTextField (5);
        btCadastrar = new JButton ("Cadastrar");
        jcomp16 = new JLabel ("Responsável por:");
        jcomp17 = new JTextField (5);
        jcomp18 = new JButton ("Sair");

        //adjust size and set layout
        setPreferredSize (new Dimension (444, 284));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (cbParentesco);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);
        add (jcomp14);
        add (btCadastrar);
        add (jcomp16);
        add (jcomp17);
        add (jcomp18);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (140, 40, 155, 25);
        jcomp2.setBounds (15, 15, 100, 25);
        jcomp3.setBounds (15, 85, 100, 25);
        jcomp4.setBounds (15, 115, 100, 25);
        jcomp5.setBounds (15, 145, 100, 25);
        jcomp6.setBounds (185, 145, 100, 25);
        cbParentesco.setBounds (295, 145, 100, 25);
        jcomp8.setBounds (75, 85, 245, 20);
        jcomp9.setBounds (100, 115, 105, 20);
        jcomp10.setBounds (220, 115, 100, 25);
        jcomp11.setBounds (265, 110, 100, 25);
        jcomp12.setBounds (70, 145, 105, 20);
        jcomp13.setBounds (15, 175, 100, 25);
        jcomp14.setBounds (80, 175, 345, 20);
        btCadastrar.setBounds (325, 240, 100, 25);
        jcomp16.setBounds (15, 205, 100, 25);
        jcomp17.setBounds (120, 205, 255, 20);
        jcomp18.setBounds (15, 240, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Cadastro Responsável");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Cadastro Responsável());
        frame.pack();
        frame.setVisible (true);
    }
}
