//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Cadastro Aluno extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JLabel jcomp6;
    private JComboBox Idioma;
    private JTextField jcomp8;
    private JTextField jcomp9;
    private JLabel jcomp10;
    private JComboBox jcomp11;
    private JTextField jcomp12;
    private JLabel jcomp13;
    private JTextField jcomp14;
    private JButton btFinanceiro;
    private JButton btResponsavel;
    private JButton btCadastrar;
    private JButton jcomp18;

    public Cadastro Aluno() {
        //construct preComponents
        String[] IdiomaItems = {"Ingles", "Frances", "Portugues", "Espanhol", "Alemao", "Italiano"};
        String[] jcomp11Items = {"F", "M", "G", "L", "T", "N/B", "N/A"};

        //construct components
        jcomp1 = new JLabel ("Cadastro de aluno");
        jcomp2 = new JLabel ("Simple Solution");
        jcomp3 = new JLabel ("Nome:");
        jcomp4 = new JLabel ("Data Nasc. :");
        jcomp5 = new JLabel ("Cidade:");
        jcomp6 = new JLabel ("Idioma desejado:");
        Idioma = new JComboBox (IdiomaItems);
        jcomp8 = new JTextField (5);
        jcomp9 = new JTextField (5);
        jcomp10 = new JLabel ("Sexo:");
        jcomp11 = new JComboBox (jcomp11Items);
        jcomp12 = new JTextField (5);
        jcomp13 = new JLabel ("Endereco:");
        jcomp14 = new JTextField (5);
        btFinanceiro = new JButton ("Financeiro");
        btResponsavel = new JButton ("Responsavel");
        btCadastrar = new JButton ("Cadastrar");
        jcomp18 = new JButton ("Sair");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 366));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (Idioma);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);
        add (jcomp14);
        add (btFinanceiro);
        add (btResponsavel);
        add (btCadastrar);
        add (jcomp18);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (160, 40, 120, 25);
        jcomp2.setBounds (15, 15, 100, 25);
        jcomp3.setBounds (15, 85, 100, 25);
        jcomp4.setBounds (15, 115, 100, 25);
        jcomp5.setBounds (15, 145, 100, 25);
        jcomp6.setBounds (185, 145, 100, 25);
        Idioma.setBounds (295, 145, 100, 25);
        jcomp8.setBounds (75, 85, 245, 20);
        jcomp9.setBounds (100, 115, 105, 20);
        jcomp10.setBounds (220, 115, 100, 25);
        jcomp11.setBounds (265, 110, 100, 25);
        jcomp12.setBounds (70, 145, 105, 20);
        jcomp13.setBounds (15, 175, 100, 25);
        jcomp14.setBounds (80, 175, 345, 20);
        btFinanceiro.setBounds (15, 225, 120, 25);
        btResponsavel.setBounds (15, 260, 120, 25);
        btCadastrar.setBounds (325, 215, 100, 25);
        jcomp18.setBounds (325, 285, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Cadastro Aluno");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Cadastro Aluno());
        frame.pack();
        frame.setVisible (true);
    }
}
