//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Cadastro Funcionário extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JTextField jcomp6;
    private JTextField jcomp7;
    private JLabel jcomp8;
    private JComboBox jcomp9;
    private JTextField jcomp10;
    private JLabel jcomp11;
    private JTextField jcomp12;
    private JButton btCadastrar;
    private JLabel jcomp14;
    private JComboBox jcomp15;
    private JLabel jcomp16;
    private JComboBox jcomp17;
    private JButton jcomp18;

    public Cadastro Funcionário() {
        //construct preComponents
        String[] jcomp9Items = {"F", "M", "G", "L", "T", "N/B", "N/A"};
        String[] jcomp15Items = {"Professor", "Diretor", "Atendente", "Coordenador", "Monitor"};
        String[] jcomp17Items = {"Inglês", "Italiano", "Português", "Espanhol"};

        //construct components
        jcomp1 = new JLabel ("Cadastro de Funcionário");
        jcomp2 = new JLabel ("Simple Solution");
        jcomp3 = new JLabel ("Nome:");
        jcomp4 = new JLabel ("Data Nasc. :");
        jcomp5 = new JLabel ("Cidade:");
        jcomp6 = new JTextField (5);
        jcomp7 = new JTextField (5);
        jcomp8 = new JLabel ("Sexo:");
        jcomp9 = new JComboBox (jcomp9Items);
        jcomp10 = new JTextField (5);
        jcomp11 = new JLabel ("Endereço:");
        jcomp12 = new JTextField (5);
        btCadastrar = new JButton ("Cadastrar");
        jcomp14 = new JLabel ("Cargo:");
        jcomp15 = new JComboBox (jcomp15Items);
        jcomp16 = new JLabel ("Idioma:");
        jcomp17 = new JComboBox (jcomp17Items);
        jcomp18 = new JButton ("Sair");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 366));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (btCadastrar);
        add (jcomp14);
        add (jcomp15);
        add (jcomp16);
        add (jcomp17);
        add (jcomp18);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (140, 40, 155, 25);
        jcomp2.setBounds (15, 15, 100, 25);
        jcomp3.setBounds (15, 85, 100, 25);
        jcomp4.setBounds (15, 115, 100, 25);
        jcomp5.setBounds (15, 145, 100, 25);
        jcomp6.setBounds (75, 85, 245, 20);
        jcomp7.setBounds (100, 115, 105, 20);
        jcomp8.setBounds (220, 115, 100, 25);
        jcomp9.setBounds (265, 110, 100, 25);
        jcomp10.setBounds (70, 145, 105, 20);
        jcomp11.setBounds (15, 175, 100, 25);
        jcomp12.setBounds (80, 175, 345, 20);
        btCadastrar.setBounds (320, 205, 100, 25);
        jcomp14.setBounds (215, 140, 100, 25);
        jcomp15.setBounds (260, 140, 100, 25);
        jcomp16.setBounds (15, 205, 100, 25);
        jcomp17.setBounds (70, 205, 100, 25);
        jcomp18.setBounds (320, 265, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Cadastro Funcionário");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Cadastro Funcionário());
        frame.pack();
        frame.setVisible (true);
    }
}
