//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Documentacao extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JComboBox jcomp3;
    private JRadioButton jcomp4;
    private JRadioButton jcomp5;
    private JTextField jcomp6;
    private JButton btSolicitar;
    private JButton jcomp8;

    public Documentacao() {
        //construct preComponents
        String[] jcomp3Items = {"Declaracao", "Copia de Contrato", "Recibo de pagamento", "Historico escolar"};

        //construct components
        jcomp1 = new JLabel ("Documentacao");
        jcomp2 = new JLabel ("Por favor selecione o tipo de documentacao:");
        jcomp3 = new JComboBox (jcomp3Items);
        jcomp4 = new JRadioButton ("Retirar na escola");
        jcomp5 = new JRadioButton ("Enviar no e-mail: ");
        jcomp6 = new JTextField (5);
        btSolicitar = new JButton ("Solicitar");
        jcomp8 = new JButton ("Sair");

        //set components properties
        jcomp6.setToolTipText ("Insira o e-mail");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 366));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (btSolicitar);
        add (jcomp8);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (190, 25, 100, 25);
        jcomp2.setBounds (40, 80, 285, 40);
        jcomp3.setBounds (40, 125, 100, 25);
        jcomp4.setBounds (45, 165, 135, 25);
        jcomp5.setBounds (45, 195, 140, 25);
        jcomp6.setBounds (185, 195, 160, 20);
        btSolicitar.setBounds (370, 230, 100, 25);
        jcomp8.setBounds (370, 265, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Documentacao");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Documentacao());
        frame.pack();
        frame.setVisible (true);
    }
}
