//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Financeiro extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JTextField jcomp4;
    private JTextArea jcomp5;
    private JButton btSalvar;
    private JLabel jcomp7;
    private JComboBox jcomp8;
    private JLabel jcomp9;
    private JLabel jcomp10;
    private JTextField jcomp11;
    private JRadioButton jcomp12;
    private JRadioButton jcomp13;
    private JRadioButton jcomp14;
    private JLabel jcomp15;
    private JButton jcomp16;

    public Financeiro() {
        //construct preComponents
        String[] jcomp8Items = {"Debito", "Credito", "Cheque", "Boleto"};

        //construct components
        jcomp1 = new JLabel ("Financeiro");
        jcomp2 = new JLabel ("Simple Solution");
        jcomp3 = new JLabel ("Nome:");
        jcomp4 = new JTextField (5);
        jcomp5 = new JTextArea (5, 5);
        btSalvar = new JButton ("Salvar");
        jcomp7 = new JLabel ("Modo pagamento:");
        jcomp8 = new JComboBox (jcomp8Items);
        jcomp9 = new JLabel ("Descrição do pagamento:");
        jcomp10 = new JLabel ("Data pag:");
        jcomp11 = new JTextField (5);
        jcomp12 = new JRadioButton ("10%");
        jcomp13 = new JRadioButton ("15%");
        jcomp14 = new JRadioButton ("20% ");
        jcomp15 = new JLabel ("Desconto:");
        jcomp16 = new JButton ("Sair");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 366));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (btSalvar);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);
        add (jcomp14);
        add (jcomp15);
        add (jcomp16);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (180, 50, 155, 25);
        jcomp2.setBounds (15, 15, 100, 25);
        jcomp3.setBounds (25, 100, 100, 25);
        jcomp4.setBounds (75, 100, 145, 25);
        jcomp5.setBounds (25, 205, 260, 70);
        btSalvar.setBounds (315, 300, 100, 25);
        jcomp7.setBounds (25, 140, 115, 25);
        jcomp8.setBounds (135, 140, 100, 25);
        jcomp9.setBounds (25, 175, 155, 25);
        jcomp10.setBounds (245, 140, 100, 25);
        jcomp11.setBounds (310, 140, 100, 25);
        jcomp12.setBounds (305, 200, 100, 25);
        jcomp13.setBounds (305, 225, 100, 25);
        jcomp14.setBounds (305, 250, 100, 25);
        jcomp15.setBounds (295, 175, 100, 25);
        jcomp16.setBounds (25, 300, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Financeiro");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Financeiro());
        frame.pack();
        frame.setVisible (true);
    }
}
