//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Inicio extends JPanel {
    private JButton btAluno;
    private JButton btProfessor;
    private JButton btAdm;
    private JLabel lb1;
    private JLabel jcomp5;
    private JLabel lb2;

    public Inicio() {
        //construct components
        btAluno = new JButton ("Aluno");
        btProfessor = new JButton ("Professor");
        btAdm = new JButton ("Adm");
        lb1 = new JLabel ("Selecione o tipo de login:");
        jcomp5 = new JLabel ("");
        lb2 = new JLabel ("Simple Solution");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 366));
        setLayout (null);

        //add components
        add (btAluno);
        add (btProfessor);
        add (btAdm);
        add (lb1);
        add (jcomp5);
        add (lb2);

        //set component bounds (only needed by Absolute Positioning)
        btAluno.setBounds (255, 130, 100, 20);
        btProfessor.setBounds (255, 160, 100, 20);
        btAdm.setBounds (255, 190, 100, 20);
        lb1.setBounds (125, 90, 200, 25);
        jcomp5.setBounds (70, 15, 100, 25);
        lb2.setBounds (5, 0, 216, 46);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Inicio");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Inicio());
        frame.pack();
        frame.setVisible (true);
    }
}
