//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MenuAdm extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JButton btCadastroAluno;
    private JButton btDesempenho;
    private JButton btCadastroFuncionario;
    private JButton btCalendario;
    private JButton btDocumentacao;
    private JButton jcomp8;

    public MenuAdm() {
        //construct components
        jcomp1 = new JLabel ("Olá, administração!");
        jcomp2 = new JLabel ("Simple Solution");
        btCadastroAluno = new JButton ("Cadastrar aluno");
        btDesempenho = new JButton ("Desempenho");
        btCadastroFuncionario = new JButton ("Cadastrar Funcionário");
        btCalendario = new JButton ("Calendário");
        btDocumentacao = new JButton ("Documentação");
        jcomp8 = new JButton ("Sair");

        //adjust size and set layout
        setPreferredSize (new Dimension (465, 321));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (btCadastroAluno);
        add (btDesempenho);
        add (btCadastroFuncionario);
        add (btCalendario);
        add (btDocumentacao);
        add (jcomp8);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (45, 80, 120, 25);
        jcomp2.setBounds (15, 15, 100, 25);
        btCadastroAluno.setBounds (40, 130, 165, 30);
        btDesempenho.setBounds (40, 180, 165, 30);
        btCadastroFuncionario.setBounds (235, 130, 165, 30);
        btCalendario.setBounds (235, 180, 165, 30);
        btDocumentacao.setBounds (40, 230, 165, 30);
        jcomp8.setBounds (350, 285, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MenuAdm");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MenuAdm());
        frame.pack();
        frame.setVisible (true);
    }
}
