//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MenuAluno extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JButton btRematricula;
    private JButton btDesempenho;
    private JButton btDocumentacao;
    private JButton btCalendario;
    private JButton jcomp7;

    public MenuAluno() {
        //construct components
        jcomp1 = new JLabel ("Ola, aluno!");
        jcomp2 = new JLabel ("Simple Solution");
        btRematricula = new JButton ("Rematricula");
        btDesempenho = new JButton ("Desempenho");
        btDocumentacao = new JButton ("Documentacao");
        btCalendario = new JButton ("Calendario");
        jcomp7 = new JButton ("Sair");

        //adjust size and set layout
        setPreferredSize (new Dimension (392, 320));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (btRematricula);
        add (btDesempenho);
        add (btDocumentacao);
        add (btCalendario);
        add (jcomp7);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (110, 75, 100, 25);
        jcomp2.setBounds (15, 15, 100, 25);
        btRematricula.setBounds (45, 130, 115, 25);
        btDesempenho.setBounds (45, 170, 115, 25);
        btDocumentacao.setBounds (175, 130, 120, 25);
        btCalendario.setBounds (175, 170, 120, 25);
        jcomp7.setBounds (235, 230, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MenuAluno");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MenuAluno());
        frame.pack();
        frame.setVisible (true);
    }
}
