//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Rematricula extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;
    private JTextField jcomp4;
    private JTextArea jcomp5;
    private JLabel jcomp6;
    private JLabel jcomp7;
    private JTextField jcomp8;
    private JTextField jcomp9;
    private JButton btRematricular;
    private JButton btFinanceiro;
    private JButton jcomp12;

    public Rematricula() {
        //construct components
        jcomp1 = new JLabel ("Rematrícula");
        jcomp2 = new JLabel ("Simple Solution");
        jcomp3 = new JLabel ("Nome:");
        jcomp4 = new JTextField (5);
        jcomp5 = new JTextArea (5, 5);
        jcomp6 = new JLabel ("Turma:");
        jcomp7 = new JLabel ("Nível:");
        jcomp8 = new JTextField (5);
        jcomp9 = new JTextField (5);
        btRematricular = new JButton ("Rematricular");
        btFinanceiro = new JButton ("Financeiro");
        jcomp12 = new JButton ("Sair");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 366));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (btRematricular);
        add (btFinanceiro);
        add (jcomp12);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (135, 35, 155, 25);
        jcomp2.setBounds (15, 15, 100, 25);
        jcomp3.setBounds (15, 75, 100, 25);
        jcomp4.setBounds (55, 75, 145, 25);
        jcomp5.setBounds (25, 175, 260, 95);
        jcomp6.setBounds (215, 70, 100, 25);
        jcomp7.setBounds (220, 110, 100, 25);
        jcomp8.setBounds (265, 75, 100, 25);
        jcomp9.setBounds (265, 115, 100, 25);
        btRematricular.setBounds (305, 165, 120, 30);
        btFinanceiro.setBounds (75, 135, 100, 25);
        jcomp12.setBounds (305, 245, 120, 30);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Rematricula");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Rematricula());
        frame.pack();
        frame.setVisible (true);
    }
}
